author:
  email: Rob@ProTechBuilder.com
  name: Rob Rutherford
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.27484587230719626
  lightness: 0.40771995135582983
  rhythmicContrast: 0.6613924019038677
  saturation: 0.1742535107769072
layout_spectrum: 1
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/6c0c43e3-e195-425b-8d11-608f317f63bf.jpg
name: Modularhomestore
title: Building one House at a time... Just for you!
typography_spectrum: 0.06879657646641135
